### ISSUE TITLE
Smooch Webhook - Bad Request

### ISSUE THREAD

**Issue by jpventura** [smooch/smooch-bot-example#26]
After 2016-10-21, I am not being able to create new webhooks and obtaining the following error running `heroku web local`:

```
2:52:17 PM web.1 |  > smooch-bot-example@1.0.1 start smooch-bot-example
2:52:17 PM web.1 |  > node heroku
2:52:19 PM web.1 |  Smooch Bot listening at http://:::5000
2:52:20 PM web.1 |  Error creating Smooch webhook: { Error: Bad Request
2:52:20 PM web.1 |      at handleStatus (/smooch-bot-example/node_modules/smooch-core/lib/utils/http.js:45:17)
2:52:20 PM web.1 |      at process._tickCallback (internal/process/next_tick.js:103:7)
2:52:20 PM web.1 |    response: 
2:52:20 PM web.1 |     Body {
2:52:20 PM web.1 |       url: 'https://api.smooch.io/v1/webhooks',
2:52:20 PM web.1 |       status: 400,
2:52:20 PM web.1 |       statusText: 'Bad Request',
2:52:20 PM web.1 |       headers: Headers { _headers: [Object] },
2:52:20 PM web.1 |       ok: false,
2:52:20 PM web.1 |       body: 
2:52:20 PM web.1 |        PassThrough {
2:52:20 PM web.1 |          _readableState: [Object],
2:52:20 PM web.1 |          readable: true,
2:52:20 PM web.1 |          domain: null,
2:52:20 PM web.1 |          _events: [Object],
2:52:20 PM web.1 |          _eventsCount: 1,
2:52:20 PM web.1 |          _maxListeners: undefined,
2:52:20 PM web.1 |          _writableState: [Object],
2:52:20 PM web.1 |          writable: false,
2:52:20 PM web.1 |          allowHalfOpen: true,
2:52:20 PM web.1 |          _transformState: [Object] },
2:52:20 PM web.1 |       bodyUsed: false,
2:52:20 PM web.1 |       size: 0,
2:52:20 PM web.1 |       timeout: 0,
2:52:20 PM web.1 |       _raw: [],
2:52:20 PM web.1 |       _abort: false } }
2:52:20 PM web.1 |  Error: Bad Request
2:52:20 PM web.1 |      at handleStatus (/smooch-bot-example/node_modules/smooch-core/lib/utils/http.js:45:17)
2:52:20 PM web.1 |      at process._tickCallback (internal/process/next_tick.js:103:7)
```

However, using the bearer token created by the application, I successfully create a webhook using curl (as described at [Smooch documentation](http://docs.smooch.io/rest/?shell#create-webhook)).

```
curl https://api.smooch.io/v1/webhooks \
     -X POST \
     -d '{"target": "http://example.com/callback"}' \
     -H 'content-type: application/json' \
     -H 'authorization: Bearer your-jwt'
```

**Comment by jpventura** [comment]
Invoking

```
curl https://api.smooch.io/v1/webhooks \
     -X POST \
     -d '{"target": "example.com/callback"}' \
     -H 'content-type: application/json' \
     -H 'authorization: Bearer your-jwt'
```

explicitly informs the user that the target url is malformed (i.e. the http or https prefix is missing), while the [`smooch-core`](https://www.npmjs.com/package/smooch-core) library throws `Bad Request` error.

A [pull request](https://github.com/smooch/smooch-core-js/pull/48) was already sent to [`smooch-core-js`](https://github.com/smooch/smooch-core-js).
